### PR TITLE
proper release tracking.

### PR DESCRIPTION
**Pull request by tijoytom**

### CODE REVIEW

**Comment by tijoytom** [comment]
@eyberg The new release structure.

Nightly :   $HOME/.ops/nightly/nanos-nightly-linux.tar.gz , no versioning , auto-update.
Release:  $HOME/.ops/0.9/nanos-release-linux-0.9.tar.gz, versioned, prompt user for update.

I don't see the need to version nightly, so it use a timestamp to look for updates.

**Comment by eyberg** [comment]
i don't find it necessary to keep multiple versions locally at all - just knowing what version someone is on should be enough - is there a reason to keep multiple versions?

**Comment by tijoytom** [comment]
I think it might be useful in future, say something worked on version x, but not on version y, it don't cost any thing to keep multiple version, just disk space. Also to mentioned  versions are pulled in on demand, we don't download them unless someone ask for it.

**Comment by eyberg** [comment]
i guess i'm not opposed to this but then you need to have a switch to switch between them && keep track of whatever is 'latest'

**Comment by tijoytom** [comment]
It knows the latest, there is a latest.txt on gcp which tells it about the latest l. That's how it detect new releases too

**Comment by eyberg** [comment]
all of this looks related but not sure the order of merge - prob best to get versioning in ~/.ops/ sorted out first

https://github.com/nanovms/ops/pull/195
https://github.com/nanovms/ops/pull/208
https://github.com/nanovms/ops/issues/135

**Comment by tijoytom** [comment]
Some of it overlap, once I merge mine, I will cherry pick from the rest

**Comment by anikitenko** [comment]
I think it's better that you first merge your PR. Right after your merge I'll check your changes and update my 2 PRs.

**Comment by tijoytom** [comment]
<pre><font color="#8AE234"><b>➜  </b></font><font color="#34E2E2"><b>.ops</b></font> tree
<font color="#729FCF"><b>.</b></font>
├── <font color="#729FCF"><b>0.9</b></font>
│   ├── boot.img
│   ├── <font color="#8AE234"><b>mkfs</b></font>
│   ├── <font color="#EF2929"><b>nanos-release-linux-0.9.tar.gz</b></font>
│   └── <font color="#8AE234"><b>stage3.img</b></font>
├── <font color="#729FCF"><b>images</b></font>
│   └── image
├── <font color="#8AE234"><b>latest.txt</b></font>
├── <font color="#729FCF"><b>nightly</b></font>
│   ├── boot.img
│   ├── <font color="#8AE234"><b>mkfs</b></font>
│   ├── <font color="#EF2929"><b>nanos-nightly-linux.tar.gz</b></font>
│   ├── <font color="#8AE234"><b>nanos-nightly-linux.timestamp</b></font>
│   └── <font color="#8AE234"><b>stage3.img</b></font>
└── <font color="#729FCF"><b>packages</b></font></pre>

**Pull request merged**
