### PR TITLE
Added bash completion script

### PR DESCRIPTION
**Pull request by arknable**
Added bash autocomplete script for ops commands

### CODE REVIEW

**Comment by arknable** [comment]
@eyberg is there any document about installation package which being put in the cloud storage ? I need to put the bash script into that package.

**Comment by fabioDMFerreira** [comment]
it is in this repo https://github.com/nanovms/ops/blob/master/install.sh

**Comment by arknable** [comment]
@fabioDMFerreira oh I just noticed this code
```
if [ "$ARCH" = "aarch64" ]; then
    BINARY_URL="$RELEASES_URL/${OS}/${ARCH}/ops"
  else 
    BINARY_URL="$RELEASES_URL/${OS}/ops"
  fi
  ```
  
  I thought we download somekind of zipped package. so which script that put `ops` binary to cloud ? I need to put `bash_completion.sh` script to the cloud also.

**Comment by arknable** [comment]
@eyberg Completion script added to installation process.

**Review by eyberg — APPROVED** [review]

**Pull request merged**
