### PR TITLE
Rename IPAddr -> IPAddress

### PR DESCRIPTION
**Pull request by am11**
https://github.com/nanovms/ops-documentation/issues/176#issuecomment-796609494

### CODE REVIEW

**Comment by am11** [comment]
@fabioDMFerreira, should we rename this as well https://github.com/nanovms/ops/blob/134ea4645201cd283ad47e3ca00814d1fac331bc/fs/manifest.go#L45-L46

**Comment by fabioDMFerreira** [comment]
> @fabioDMFerreira, should we rename this as well
> 
> https://github.com/nanovms/ops/blob/134ea4645201cd283ad47e3ca00814d1fac331bc/fs/manifest.go#L45-L46

please don't change `m.root["ipaddr"]` as this is read by nanos

**Comment by am11** [comment]
ok, i haven't change it.

**Comment by fabioDMFerreira** [comment]
Seems good to me. We can merge it after updating the documentation.

**Pull request merged**
