### PR TITLE
use kernel.img for nightly

### LINKED ISSUE #594: stage3.img does not exist in nightly
when using `nightly`, `stage3.img` is required but there is only `kernel.img` under `~/.ops/nightly`, not sure if this is the intended behavior

### PR DESCRIPTION
**Pull request by ronaudinho**
resolve #594

### CODE REVIEW

**Comment by eyberg** [comment]
looks like it broke here -> https://github.com/nanovms/nanos/commit/f44463b1a2dfa9ad367ea4941cc5765690fecf3e - although versioned releases still use 'stage3'  - i'm ok w/this fix but i think it also makes sense to keep the name consistent so if @wjhun doesn't mind maybe you can fix the .circleci/config line there?

**Comment by francescolavra** [comment]
The old stage3.img file name is not used anymore in the kernel, and the new kernel.img file name is now referenced in many places if the kernel Makefiles, so if we just change the .circleci/config line there, it would break the CI build.
So, either we revert all the file name changes in the kernel, or Ops will have to use the new file name.

**Comment by eyberg** [comment]
that's fine - we can just update any name refs in this repo && cut a new release and it should be fine

**Comment by eyberg** [comment]
@ronaudinho might be good just to rename all refs and then we'll merge this

```
➜  ops git:(master) ✗ grep -R stage3 * | grep -v vendor
cmd/root_test.go:       kernel := path.Join(api.GetOpsHome(), api.LatestReleaseVersion, "stage3.img")
cmd/utils.go:           c.Kernel = path.Join(api.GetOpsHome(), version, "stage3.img")
lepton/manifest_test.go:        kernel = `kernel:(contents:(host:stage3/stage3))
lepton/manifest_test.go:        m.AddKernel("stage3/stage3")
lepton/manifest_test.go:        m.AddKernel("stage3/stage3")
```

**Comment by ronaudinho** [comment]
renamed all `stage3` and added a quick hack in the last commit, will take out if unnecessary.

**Comment by eyberg** [comment]
i'm merging this now as I need to cut new releases for both nanos/ops

**Pull request merged**
